### ISSUE TITLE
Suggestions for improvement

### ISSUE THREAD

**Issue by zerolab** [kaedroho/cookiecutter-wagtail-plugin#1]
Nice package @kaedroho !
A few nice to haves:

* add `Framework :: Wagtail :: 2` to classifiers in setup.py
* make author/email configurable
* make `register_admin_urls` a placeholder (currently it has a very specific package [implementation](https://github.com/kaedroho/cookiecutter-wagtail-plugin/blob/main/wagtail-%7B%7B%20cookiecutter.project_name_kebab%20%7D%7D/wagtail_%7B%7B%20cookiecutter.project_name_snake%20%7D%7D/wagtail_hooks.py#L10))

**Comment by kaedroho** [comment]
Thanks! Sorry I missed this earlier, it looks like the first two points are implemented.

On the third point, I'd rather keep that there since it's useful for any plugin that has translatable strings in JavaScript. I use this quite a lot!
